### ISSUE TITLE
Installation fails with package evernote==1.25.2

### ISSUE THREAD

**Issue by SprickW** [kostya0shift/SyncToGit#2]
pip install synctogit fails (see below)

Environment: Ubuntu 20.04 LTS
Python 3.8.10
pip 20.0.2 

pip install synctogit
Collecting synctogit
  Downloading synctogit-2.0.1.tar.gz (35 kB)
Collecting oauth2==1.9.0.post1
  Using cached oauth2-1.9.0.post1-py2.py3-none-any.whl (25 kB)
Collecting GitPython==2.0.8
  Downloading GitPython-2.0.8.tar.gz (407 kB)
     |████████████████████████████████| 407 kB 5.8 MB/s 
Collecting defusedxml==0.4.1
  Downloading defusedxml-0.4.1.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 5.4 MB/s 
Collecting regex==2016.7.21
  Downloading regex-2016.07.21.tar.gz (598 kB)
     |████████████████████████████████| 598 kB 11.8 MB/s 
Collecting evernote==1.25.2
  Downloading evernote-1.25.2.tar.gz (141 kB)
     |████████████████████████████████| 141 kB 10.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/sprickw/PycharmProjects/files_and_database/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ok46u2sb/evernote/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ok46u2sb/evernote/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ok46u2sb/evernote/pip-egg-info
         cwd: /tmp/pip-install-ok46u2sb/evernote/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ok46u2sb/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by KostyaEsmukov** [comment]
I haven't pushed the latest changes to PyPI. The package can be installed via git: `pip install 'git+https://github.com/KostyaEsmukov/SyncToGit.git@82fb8f6#egg=synctogit[evernote]'`

**Comment by SprickW** [comment]
Still problem installing:

Building wheels for collected packages: synctogit
  Building wheel for synctogit (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sprickw/PycharmProjects/files_and_database/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-skzzrn9l/synctogit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-skzzrn9l/synctogit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1phjicxz
       cwd: /tmp/pip-install-skzzrn9l/synctogit/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for synctogit
  Running setup.py clean for synctogit
Failed to build synctogit
